---
repo-name: peripherals-google-apps
categories:
- Collaboration
- Messaging
display-name: Google Apps
manufacture: Google
product: 
description: Google Apps is a Web-based and collaborative Software as a Service (SaaS) solution that customizes the proprietary Google platform and brand for businesses of all sizes, including large enterprises.
